### Get all events

GET http://localhost:3000/events


### Create a new event (should succeed)
POST http://localhost:3000/events
Content-Type: application/json

{
    "name": "Event",
    "description": "Some description",
    "date": "2022-06-06T01:00:00.000Z",
    "presenter": "Geoff Reid",
    "is_english": false,
    "is_domestic": false,
    "is_common": false
}

### Create a new event (should fail - no name)
POST http://localhost:3000/events
Content-Type: application/json

{
    "description": "Some description",
    "date": "2022-06-06T01:00:00.000Z",
    "presenter": "Geoff Reid",
    "is_english": false,
    "is_domestic": false,
    "is_common": false
}

### Show event id: 8 (should succeed)
GET http://localhost:3000/events/8

### Show event id: 8 (should fail - no event at id 1)
GET http://localhost:3000/events/1

### Update event id:8 name (should succeed)
PUT http://localhost:3000/events/8
Content-Type: application/json

{
    "name": "Event update",
}

### Delete event id:4
DELETE http://localhost:3000/events/4
